// Code generated by ogen, DO NOT EDIT.

package api

import (
	"time"

	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
	"github.com/ogen-go/ogen/json"
)

// Encode implements json.Marshaler.
func (s *License) Encode(e *jx.Encoder) {
	e.ObjStart()
	s.encodeFields(e)
	e.ObjEnd()
}

// encodeFields encodes fields.
func (s *License) encodeFields(e *jx.Encoder) {
	{
		if s.Contents.Set {
			e.FieldStart("contents")
			s.Contents.Encode(e)
		}
	}
	{
		if s.FilePath.Set {
			e.FieldStart("filePath")
			s.FilePath.Encode(e)
		}
	}
	{
		if s.Types != nil {
			e.FieldStart("types")
			e.ArrStart()
			for _, elem := range s.Types {
				e.Str(elem)
			}
			e.ArrEnd()
		}
	}
}

var jsonFieldsNameOfLicense = [3]string{
	0: "contents",
	1: "filePath",
	2: "types",
}

// Decode decodes License from json.
func (s *License) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode License to nil")
	}

	if err := d.ObjBytes(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "contents":
			if err := func() error {
				s.Contents.Reset()
				if err := s.Contents.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"contents\"")
			}
		case "filePath":
			if err := func() error {
				s.FilePath.Reset()
				if err := s.FilePath.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"filePath\"")
			}
		case "types":
			if err := func() error {
				s.Types = make([]string, 0)
				if err := d.Arr(func(d *jx.Decoder) error {
					var elem string
					v, err := d.Str()
					elem = string(v)
					if err != nil {
						return err
					}
					s.Types = append(s.Types, elem)
					return nil
				}); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"types\"")
			}
		default:
			return d.Skip()
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode License")
	}

	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s *License) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *License) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode implements json.Marshaler.
func (s *Module) Encode(e *jx.Encoder) {
	e.ObjStart()
	s.encodeFields(e)
	e.ObjEnd()
}

// encodeFields encodes fields.
func (s *Module) encodeFields(e *jx.Encoder) {
	{
		if s.CommitTime.Set {
			e.FieldStart("commitTime")
			s.CommitTime.Encode(e, json.EncodeDateTime)
		}
	}
	{
		if s.GoModContents.Set {
			e.FieldStart("goModContents")
			s.GoModContents.Encode(e)
		}
	}
	{
		if s.HasGoMod.Set {
			e.FieldStart("hasGoMod")
			s.HasGoMod.Encode(e)
		}
	}
	{
		if s.IsLatest.Set {
			e.FieldStart("isLatest")
			s.IsLatest.Encode(e)
		}
	}
	{
		if s.IsRedistributable.Set {
			e.FieldStart("isRedistributable")
			s.IsRedistributable.Encode(e)
		}
	}
	{
		if s.IsStandardLibrary.Set {
			e.FieldStart("isStandardLibrary")
			s.IsStandardLibrary.Encode(e)
		}
	}
	{
		if s.Licenses != nil {
			e.FieldStart("licenses")
			e.ArrStart()
			for _, elem := range s.Licenses {
				elem.Encode(e)
			}
			e.ArrEnd()
		}
	}
	{
		if s.Path.Set {
			e.FieldStart("path")
			s.Path.Encode(e)
		}
	}
	{
		if s.Readme.Set {
			e.FieldStart("readme")
			s.Readme.Encode(e)
		}
	}
	{
		if s.RepoUrl.Set {
			e.FieldStart("repoUrl")
			s.RepoUrl.Encode(e)
		}
	}
	{
		if s.Version.Set {
			e.FieldStart("version")
			s.Version.Encode(e)
		}
	}
}

var jsonFieldsNameOfModule = [11]string{
	0:  "commitTime",
	1:  "goModContents",
	2:  "hasGoMod",
	3:  "isLatest",
	4:  "isRedistributable",
	5:  "isStandardLibrary",
	6:  "licenses",
	7:  "path",
	8:  "readme",
	9:  "repoUrl",
	10: "version",
}

// Decode decodes Module from json.
func (s *Module) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode Module to nil")
	}

	if err := d.ObjBytes(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "commitTime":
			if err := func() error {
				s.CommitTime.Reset()
				if err := s.CommitTime.Decode(d, json.DecodeDateTime); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"commitTime\"")
			}
		case "goModContents":
			if err := func() error {
				s.GoModContents.Reset()
				if err := s.GoModContents.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"goModContents\"")
			}
		case "hasGoMod":
			if err := func() error {
				s.HasGoMod.Reset()
				if err := s.HasGoMod.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"hasGoMod\"")
			}
		case "isLatest":
			if err := func() error {
				s.IsLatest.Reset()
				if err := s.IsLatest.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"isLatest\"")
			}
		case "isRedistributable":
			if err := func() error {
				s.IsRedistributable.Reset()
				if err := s.IsRedistributable.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"isRedistributable\"")
			}
		case "isStandardLibrary":
			if err := func() error {
				s.IsStandardLibrary.Reset()
				if err := s.IsStandardLibrary.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"isStandardLibrary\"")
			}
		case "licenses":
			if err := func() error {
				s.Licenses = make([]License, 0)
				if err := d.Arr(func(d *jx.Decoder) error {
					var elem License
					if err := elem.Decode(d); err != nil {
						return err
					}
					s.Licenses = append(s.Licenses, elem)
					return nil
				}); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"licenses\"")
			}
		case "path":
			if err := func() error {
				s.Path.Reset()
				if err := s.Path.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"path\"")
			}
		case "readme":
			if err := func() error {
				s.Readme.Reset()
				if err := s.Readme.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"readme\"")
			}
		case "repoUrl":
			if err := func() error {
				s.RepoUrl.Reset()
				if err := s.RepoUrl.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"repoUrl\"")
			}
		case "version":
			if err := func() error {
				s.Version.Reset()
				if err := s.Version.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"version\"")
			}
		default:
			return d.Skip()
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode Module")
	}

	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s *Module) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *Module) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode encodes bool as json.
func (o OptBool) Encode(e *jx.Encoder) {
	if !o.Set {
		return
	}
	e.Bool(bool(o.Value))
}

// Decode decodes bool from json.
func (o *OptBool) Decode(d *jx.Decoder) error {
	if o == nil {
		return errors.New("invalid: unable to decode OptBool to nil")
	}
	o.Set = true
	v, err := d.Bool()
	if err != nil {
		return err
	}
	o.Value = bool(v)
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s OptBool) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *OptBool) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode encodes time.Time as json.
func (o OptDateTime) Encode(e *jx.Encoder, format func(*jx.Encoder, time.Time)) {
	if !o.Set {
		return
	}
	format(e, o.Value)
}

// Decode decodes time.Time from json.
func (o *OptDateTime) Decode(d *jx.Decoder, format func(*jx.Decoder) (time.Time, error)) error {
	if o == nil {
		return errors.New("invalid: unable to decode OptDateTime to nil")
	}
	o.Set = true
	v, err := format(d)
	if err != nil {
		return err
	}
	o.Value = v
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s OptDateTime) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e, json.EncodeDateTime)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *OptDateTime) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d, json.DecodeDateTime)
}

// Encode encodes int as json.
func (o OptInt) Encode(e *jx.Encoder) {
	if !o.Set {
		return
	}
	e.Int(int(o.Value))
}

// Decode decodes int from json.
func (o *OptInt) Decode(d *jx.Decoder) error {
	if o == nil {
		return errors.New("invalid: unable to decode OptInt to nil")
	}
	o.Set = true
	v, err := d.Int()
	if err != nil {
		return err
	}
	o.Value = int(v)
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s OptInt) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *OptInt) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode encodes []jx.Raw as json.
func (o OptNilAnyArray) Encode(e *jx.Encoder) {
	if !o.Set {
		return
	}
	if o.Null {
		e.Null()
		return
	}
	e.ArrStart()
	for _, elem := range o.Value {
		if len(elem) != 0 {
			e.Raw(elem)
		}
	}
	e.ArrEnd()
}

// Decode decodes []jx.Raw from json.
func (o *OptNilAnyArray) Decode(d *jx.Decoder) error {
	if o == nil {
		return errors.New("invalid: unable to decode OptNilAnyArray to nil")
	}
	if d.Next() == jx.Null {
		if err := d.Null(); err != nil {
			return err
		}

		var v []jx.Raw
		o.Value = v
		o.Set = true
		o.Null = true
		return nil
	}
	o.Set = true
	o.Null = false
	o.Value = make([]jx.Raw, 0)
	if err := d.Arr(func(d *jx.Decoder) error {
		var elem jx.Raw
		v, err := d.RawAppend(nil)
		elem = jx.Raw(v)
		if err != nil {
			return err
		}
		o.Value = append(o.Value, elem)
		return nil
	}); err != nil {
		return err
	}
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s OptNilAnyArray) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *OptNilAnyArray) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode encodes PaginatedResponse as json.
func (o OptPaginatedResponse) Encode(e *jx.Encoder) {
	if !o.Set {
		return
	}
	o.Value.Encode(e)
}

// Decode decodes PaginatedResponse from json.
func (o *OptPaginatedResponse) Decode(d *jx.Decoder) error {
	if o == nil {
		return errors.New("invalid: unable to decode OptPaginatedResponse to nil")
	}
	o.Set = true
	if err := o.Value.Decode(d); err != nil {
		return err
	}
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s OptPaginatedResponse) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *OptPaginatedResponse) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode encodes Readme as json.
func (o OptReadme) Encode(e *jx.Encoder) {
	if !o.Set {
		return
	}
	o.Value.Encode(e)
}

// Decode decodes Readme from json.
func (o *OptReadme) Decode(d *jx.Decoder) error {
	if o == nil {
		return errors.New("invalid: unable to decode OptReadme to nil")
	}
	o.Set = true
	if err := o.Value.Decode(d); err != nil {
		return err
	}
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s OptReadme) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *OptReadme) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode encodes string as json.
func (o OptString) Encode(e *jx.Encoder) {
	if !o.Set {
		return
	}
	e.Str(string(o.Value))
}

// Decode decodes string from json.
func (o *OptString) Decode(d *jx.Decoder) error {
	if o == nil {
		return errors.New("invalid: unable to decode OptString to nil")
	}
	o.Set = true
	v, err := d.Str()
	if err != nil {
		return err
	}
	o.Value = string(v)
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s OptString) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *OptString) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode implements json.Marshaler.
func (s *Package) Encode(e *jx.Encoder) {
	e.ObjStart()
	s.encodeFields(e)
	e.ObjEnd()
}

// encodeFields encodes fields.
func (s *Package) encodeFields(e *jx.Encoder) {
	{
		if s.Docs.Set {
			e.FieldStart("docs")
			s.Docs.Encode(e)
		}
	}
	{
		if s.Goarch.Set {
			e.FieldStart("goarch")
			s.Goarch.Encode(e)
		}
	}
	{
		if s.Goos.Set {
			e.FieldStart("goos")
			s.Goos.Encode(e)
		}
	}
	{
		if s.Imports != nil {
			e.FieldStart("imports")
			e.ArrStart()
			for _, elem := range s.Imports {
				e.Str(elem)
			}
			e.ArrEnd()
		}
	}
	{
		if s.IsLatest.Set {
			e.FieldStart("isLatest")
			s.IsLatest.Encode(e)
		}
	}
	{
		if s.IsRedistributable.Set {
			e.FieldStart("isRedistributable")
			s.IsRedistributable.Encode(e)
		}
	}
	{
		if s.IsStandardLibrary.Set {
			e.FieldStart("isStandardLibrary")
			s.IsStandardLibrary.Encode(e)
		}
	}
	{
		if s.Licenses != nil {
			e.FieldStart("licenses")
			e.ArrStart()
			for _, elem := range s.Licenses {
				elem.Encode(e)
			}
			e.ArrEnd()
		}
	}
	{
		if s.ModulePath.Set {
			e.FieldStart("modulePath")
			s.ModulePath.Encode(e)
		}
	}
	{
		if s.Name.Set {
			e.FieldStart("name")
			s.Name.Encode(e)
		}
	}
	{
		if s.Path.Set {
			e.FieldStart("path")
			s.Path.Encode(e)
		}
	}
	{
		if s.Synopsis.Set {
			e.FieldStart("synopsis")
			s.Synopsis.Encode(e)
		}
	}
	{
		if s.Version.Set {
			e.FieldStart("version")
			s.Version.Encode(e)
		}
	}
}

var jsonFieldsNameOfPackage = [13]string{
	0:  "docs",
	1:  "goarch",
	2:  "goos",
	3:  "imports",
	4:  "isLatest",
	5:  "isRedistributable",
	6:  "isStandardLibrary",
	7:  "licenses",
	8:  "modulePath",
	9:  "name",
	10: "path",
	11: "synopsis",
	12: "version",
}

// Decode decodes Package from json.
func (s *Package) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode Package to nil")
	}

	if err := d.ObjBytes(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "docs":
			if err := func() error {
				s.Docs.Reset()
				if err := s.Docs.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"docs\"")
			}
		case "goarch":
			if err := func() error {
				s.Goarch.Reset()
				if err := s.Goarch.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"goarch\"")
			}
		case "goos":
			if err := func() error {
				s.Goos.Reset()
				if err := s.Goos.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"goos\"")
			}
		case "imports":
			if err := func() error {
				s.Imports = make([]string, 0)
				if err := d.Arr(func(d *jx.Decoder) error {
					var elem string
					v, err := d.Str()
					elem = string(v)
					if err != nil {
						return err
					}
					s.Imports = append(s.Imports, elem)
					return nil
				}); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"imports\"")
			}
		case "isLatest":
			if err := func() error {
				s.IsLatest.Reset()
				if err := s.IsLatest.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"isLatest\"")
			}
		case "isRedistributable":
			if err := func() error {
				s.IsRedistributable.Reset()
				if err := s.IsRedistributable.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"isRedistributable\"")
			}
		case "isStandardLibrary":
			if err := func() error {
				s.IsStandardLibrary.Reset()
				if err := s.IsStandardLibrary.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"isStandardLibrary\"")
			}
		case "licenses":
			if err := func() error {
				s.Licenses = make([]License, 0)
				if err := d.Arr(func(d *jx.Decoder) error {
					var elem License
					if err := elem.Decode(d); err != nil {
						return err
					}
					s.Licenses = append(s.Licenses, elem)
					return nil
				}); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"licenses\"")
			}
		case "modulePath":
			if err := func() error {
				s.ModulePath.Reset()
				if err := s.ModulePath.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"modulePath\"")
			}
		case "name":
			if err := func() error {
				s.Name.Reset()
				if err := s.Name.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"name\"")
			}
		case "path":
			if err := func() error {
				s.Path.Reset()
				if err := s.Path.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"path\"")
			}
		case "synopsis":
			if err := func() error {
				s.Synopsis.Reset()
				if err := s.Synopsis.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"synopsis\"")
			}
		case "version":
			if err := func() error {
				s.Version.Reset()
				if err := s.Version.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"version\"")
			}
		default:
			return d.Skip()
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode Package")
	}

	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s *Package) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *Package) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode implements json.Marshaler.
func (s *PackageImportedBy) Encode(e *jx.Encoder) {
	e.ObjStart()
	s.encodeFields(e)
	e.ObjEnd()
}

// encodeFields encodes fields.
func (s *PackageImportedBy) encodeFields(e *jx.Encoder) {
	{
		if s.ImportedBy.Set {
			e.FieldStart("importedBy")
			s.ImportedBy.Encode(e)
		}
	}
	{
		if s.ModulePath.Set {
			e.FieldStart("modulePath")
			s.ModulePath.Encode(e)
		}
	}
	{
		if s.Version.Set {
			e.FieldStart("version")
			s.Version.Encode(e)
		}
	}
}

var jsonFieldsNameOfPackageImportedBy = [3]string{
	0: "importedBy",
	1: "modulePath",
	2: "version",
}

// Decode decodes PackageImportedBy from json.
func (s *PackageImportedBy) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode PackageImportedBy to nil")
	}

	if err := d.ObjBytes(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "importedBy":
			if err := func() error {
				s.ImportedBy.Reset()
				if err := s.ImportedBy.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"importedBy\"")
			}
		case "modulePath":
			if err := func() error {
				s.ModulePath.Reset()
				if err := s.ModulePath.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"modulePath\"")
			}
		case "version":
			if err := func() error {
				s.Version.Reset()
				if err := s.Version.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"version\"")
			}
		default:
			return d.Skip()
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode PackageImportedBy")
	}

	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s *PackageImportedBy) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *PackageImportedBy) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode implements json.Marshaler.
func (s *PackageSymbols) Encode(e *jx.Encoder) {
	e.ObjStart()
	s.encodeFields(e)
	e.ObjEnd()
}

// encodeFields encodes fields.
func (s *PackageSymbols) encodeFields(e *jx.Encoder) {
	{
		if s.ModulePath.Set {
			e.FieldStart("modulePath")
			s.ModulePath.Encode(e)
		}
	}
	{
		if s.Symbols.Set {
			e.FieldStart("symbols")
			s.Symbols.Encode(e)
		}
	}
	{
		if s.Version.Set {
			e.FieldStart("version")
			s.Version.Encode(e)
		}
	}
}

var jsonFieldsNameOfPackageSymbols = [3]string{
	0: "modulePath",
	1: "symbols",
	2: "version",
}

// Decode decodes PackageSymbols from json.
func (s *PackageSymbols) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode PackageSymbols to nil")
	}

	if err := d.ObjBytes(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "modulePath":
			if err := func() error {
				s.ModulePath.Reset()
				if err := s.ModulePath.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"modulePath\"")
			}
		case "symbols":
			if err := func() error {
				s.Symbols.Reset()
				if err := s.Symbols.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"symbols\"")
			}
		case "version":
			if err := func() error {
				s.Version.Reset()
				if err := s.Version.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"version\"")
			}
		default:
			return d.Skip()
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode PackageSymbols")
	}

	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s *PackageSymbols) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *PackageSymbols) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode implements json.Marshaler.
func (s *PackagesResponse) Encode(e *jx.Encoder) {
	e.ObjStart()
	s.encodeFields(e)
	e.ObjEnd()
}

// encodeFields encodes fields.
func (s *PackagesResponse) encodeFields(e *jx.Encoder) {
	{
		if s.IsStandardLibrary.Set {
			e.FieldStart("isStandardLibrary")
			s.IsStandardLibrary.Encode(e)
		}
	}
	{
		if s.ModulePath.Set {
			e.FieldStart("modulePath")
			s.ModulePath.Encode(e)
		}
	}
	{
		if s.Packages.Set {
			e.FieldStart("packages")
			s.Packages.Encode(e)
		}
	}
	{
		if s.Version.Set {
			e.FieldStart("version")
			s.Version.Encode(e)
		}
	}
}

var jsonFieldsNameOfPackagesResponse = [4]string{
	0: "isStandardLibrary",
	1: "modulePath",
	2: "packages",
	3: "version",
}

// Decode decodes PackagesResponse from json.
func (s *PackagesResponse) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode PackagesResponse to nil")
	}

	if err := d.ObjBytes(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "isStandardLibrary":
			if err := func() error {
				s.IsStandardLibrary.Reset()
				if err := s.IsStandardLibrary.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"isStandardLibrary\"")
			}
		case "modulePath":
			if err := func() error {
				s.ModulePath.Reset()
				if err := s.ModulePath.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"modulePath\"")
			}
		case "packages":
			if err := func() error {
				s.Packages.Reset()
				if err := s.Packages.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"packages\"")
			}
		case "version":
			if err := func() error {
				s.Version.Reset()
				if err := s.Version.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"version\"")
			}
		default:
			return d.Skip()
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode PackagesResponse")
	}

	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s *PackagesResponse) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *PackagesResponse) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode implements json.Marshaler.
func (s *PaginatedResponse) Encode(e *jx.Encoder) {
	e.ObjStart()
	s.encodeFields(e)
	e.ObjEnd()
}

// encodeFields encodes fields.
func (s *PaginatedResponse) encodeFields(e *jx.Encoder) {
	{
		if s.Items.Set {
			e.FieldStart("items")
			s.Items.Encode(e)
		}
	}
	{
		if s.NextPageToken.Set {
			e.FieldStart("nextPageToken")
			s.NextPageToken.Encode(e)
		}
	}
	{
		if s.Total.Set {
			e.FieldStart("total")
			s.Total.Encode(e)
		}
	}
}

var jsonFieldsNameOfPaginatedResponse = [3]string{
	0: "items",
	1: "nextPageToken",
	2: "total",
}

// Decode decodes PaginatedResponse from json.
func (s *PaginatedResponse) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode PaginatedResponse to nil")
	}

	if err := d.ObjBytes(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "items":
			if err := func() error {
				s.Items.Reset()
				if err := s.Items.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"items\"")
			}
		case "nextPageToken":
			if err := func() error {
				s.NextPageToken.Reset()
				if err := s.NextPageToken.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"nextPageToken\"")
			}
		case "total":
			if err := func() error {
				s.Total.Reset()
				if err := s.Total.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"total\"")
			}
		default:
			return d.Skip()
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode PaginatedResponse")
	}

	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s *PaginatedResponse) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *PaginatedResponse) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode implements json.Marshaler.
func (s *Readme) Encode(e *jx.Encoder) {
	e.ObjStart()
	s.encodeFields(e)
	e.ObjEnd()
}

// encodeFields encodes fields.
func (s *Readme) encodeFields(e *jx.Encoder) {
	{
		if s.Contents.Set {
			e.FieldStart("contents")
			s.Contents.Encode(e)
		}
	}
	{
		if s.Filepath.Set {
			e.FieldStart("filepath")
			s.Filepath.Encode(e)
		}
	}
}

var jsonFieldsNameOfReadme = [2]string{
	0: "contents",
	1: "filepath",
}

// Decode decodes Readme from json.
func (s *Readme) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode Readme to nil")
	}

	if err := d.ObjBytes(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "contents":
			if err := func() error {
				s.Contents.Reset()
				if err := s.Contents.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"contents\"")
			}
		case "filepath":
			if err := func() error {
				s.Filepath.Reset()
				if err := s.Filepath.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"filepath\"")
			}
		default:
			return d.Skip()
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode Readme")
	}

	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s *Readme) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *Readme) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}
