// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	GetImportedByOperation OperationName = "GetImportedBy"
	GetModuleOperation     OperationName = "GetModule"
	GetPackageOperation    OperationName = "GetPackage"
	GetPackagesOperation   OperationName = "GetPackages"
	GetSearchOperation     OperationName = "GetSearch"
	GetSymbolsOperation    OperationName = "GetSymbols"
	GetVersionsOperation   OperationName = "GetVersions"
	GetVulnsOperation      OperationName = "GetVulns"
)
