// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// GetImportedBy implements getImported-by operation.
	//
	// Paths of packages importing the package at {path}, not including packages in the same module.
	// Filtering is applied to the list of paths in the response. Only paths that match the filter query
	// parameter are returned. Within a filter, the variable `path` is set to the import path.
	//
	// GET /imported-by/{path}
	GetImportedBy(ctx context.Context, params GetImportedByParams) (*PackageImportedBy, error)
	// GetModule implements getModule operation.
	//
	// Information about the module at {path}.
	//
	// GET /module/{path}
	GetModule(ctx context.Context, params GetModuleParams) (*Module, error)
	// GetPackage implements getPackage operation.
	//
	// Information about the package at {path}.
	//
	// GET /package/{path}
	GetPackage(ctx context.Context, params GetPackageParams) (*Package, error)
	// GetPackages implements getPackages operation.
	//
	// Information about packages of the module at {path}. Filtering is applied to the list of packages in
	// the response. Only packages that match the filter query parameter are returned.
	//
	// GET /packages/{path}
	GetPackages(ctx context.Context, params GetPackagesParams) (*PackagesResponse, error)
	// GetSearch implements getSearch operation.
	//
	// Search results. Only results that match the filter query parameter are returned. Results are sorted
	// by how well the match the query, with the best match first.
	//
	// GET /search
	GetSearch(ctx context.Context, params GetSearchParams) (*PaginatedResponse, error)
	// GetSymbols implements getSymbols operation.
	//
	// List of symbols for the package at {path}. Filtering is applied to the list of symbols in the
	// response. Only symbols that match the filter query parameter are returned.
	//
	// GET /symbols/{path}
	GetSymbols(ctx context.Context, params GetSymbolsParams) (*PackageSymbols, error)
	// GetVersions implements getVersions operation.
	//
	// Versions of the module at {path}. If there are tagged versions, they are returned. Otherwise, the 10
	// most recent pseudo-versions are returned. The versions are in descending order. Only results that
	// match the filter query parameter are returned.
	//
	// GET /versions/{path}
	GetVersions(ctx context.Context, params GetVersionsParams) (*PaginatedResponse, error)
	// GetVulns implements getVulns operation.
	//
	// Vulnerabilities of the module or package at {path}, from the Go vulnerability database
	// (https://vuln.go.dev). Only results that match the filter query parameter are returned.
	//
	// GET /vulns/{path}
	GetVulns(ctx context.Context, params GetVulnsParams) (*PaginatedResponse, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
