// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetImportedBy implements getImported-by operation.
//
// Paths of packages importing the package at {path}, not including packages in the same module.
// Filtering is applied to the list of paths in the response. Only paths that match the filter query
// parameter are returned. Within a filter, the variable `path` is set to the import path.
//
// GET /imported-by/{path}
func (UnimplementedHandler) GetImportedBy(ctx context.Context, params GetImportedByParams) (r *PackageImportedBy, _ error) {
	return r, ht.ErrNotImplemented
}

// GetModule implements getModule operation.
//
// Information about the module at {path}.
//
// GET /module/{path}
func (UnimplementedHandler) GetModule(ctx context.Context, params GetModuleParams) (r *Module, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPackage implements getPackage operation.
//
// Information about the package at {path}.
//
// GET /package/{path}
func (UnimplementedHandler) GetPackage(ctx context.Context, params GetPackageParams) (r *Package, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPackages implements getPackages operation.
//
// Information about packages of the module at {path}. Filtering is applied to the list of packages in
// the response. Only packages that match the filter query parameter are returned.
//
// GET /packages/{path}
func (UnimplementedHandler) GetPackages(ctx context.Context, params GetPackagesParams) (r *PackagesResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSearch implements getSearch operation.
//
// Search results. Only results that match the filter query parameter are returned. Results are sorted
// by how well the match the query, with the best match first.
//
// GET /search
func (UnimplementedHandler) GetSearch(ctx context.Context, params GetSearchParams) (r *PaginatedResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSymbols implements getSymbols operation.
//
// List of symbols for the package at {path}. Filtering is applied to the list of symbols in the
// response. Only symbols that match the filter query parameter are returned.
//
// GET /symbols/{path}
func (UnimplementedHandler) GetSymbols(ctx context.Context, params GetSymbolsParams) (r *PackageSymbols, _ error) {
	return r, ht.ErrNotImplemented
}

// GetVersions implements getVersions operation.
//
// Versions of the module at {path}. If there are tagged versions, they are returned. Otherwise, the 10
// most recent pseudo-versions are returned. The versions are in descending order. Only results that
// match the filter query parameter are returned.
//
// GET /versions/{path}
func (UnimplementedHandler) GetVersions(ctx context.Context, params GetVersionsParams) (r *PaginatedResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// GetVulns implements getVulns operation.
//
// Vulnerabilities of the module or package at {path}, from the Go vulnerability database
// (https://vuln.go.dev). Only results that match the filter query parameter are returned.
//
// GET /vulns/{path}
func (UnimplementedHandler) GetVulns(ctx context.Context, params GetVulnsParams) (r *PaginatedResponse, _ error) {
	return r, ht.ErrNotImplemented
}
