// Code generated by ogen, DO NOT EDIT.

package api

import (
	"time"

	"github.com/go-faster/jx"
)

// Ref: #/components/schemas/License
type License struct {
	Contents OptString `json:"contents"`
	FilePath OptString `json:"filePath"`
	Types    []string  `json:"types"`
}

// GetContents returns the value of Contents.
func (s *License) GetContents() OptString {
	return s.Contents
}

// GetFilePath returns the value of FilePath.
func (s *License) GetFilePath() OptString {
	return s.FilePath
}

// GetTypes returns the value of Types.
func (s *License) GetTypes() []string {
	return s.Types
}

// SetContents sets the value of Contents.
func (s *License) SetContents(val OptString) {
	s.Contents = val
}

// SetFilePath sets the value of FilePath.
func (s *License) SetFilePath(val OptString) {
	s.FilePath = val
}

// SetTypes sets the value of Types.
func (s *License) SetTypes(val []string) {
	s.Types = val
}

// Ref: #/components/schemas/Module
type Module struct {
	// CommitTime is the timestamp returned by the module proxy's .info endpoint, representing the time the
	// version was created.
	CommitTime        OptDateTime `json:"commitTime"`
	GoModContents     OptString   `json:"goModContents"`
	HasGoMod          OptBool     `json:"hasGoMod"`
	IsLatest          OptBool     `json:"isLatest"`
	IsRedistributable OptBool     `json:"isRedistributable"`
	IsStandardLibrary OptBool     `json:"isStandardLibrary"`
	Licenses          []License   `json:"licenses"`
	Path              OptString   `json:"path"`
	Readme            OptReadme   `json:"readme"`
	RepoUrl           OptString   `json:"repoUrl"`
	Version           OptString   `json:"version"`
}

// GetCommitTime returns the value of CommitTime.
func (s *Module) GetCommitTime() OptDateTime {
	return s.CommitTime
}

// GetGoModContents returns the value of GoModContents.
func (s *Module) GetGoModContents() OptString {
	return s.GoModContents
}

// GetHasGoMod returns the value of HasGoMod.
func (s *Module) GetHasGoMod() OptBool {
	return s.HasGoMod
}

// GetIsLatest returns the value of IsLatest.
func (s *Module) GetIsLatest() OptBool {
	return s.IsLatest
}

// GetIsRedistributable returns the value of IsRedistributable.
func (s *Module) GetIsRedistributable() OptBool {
	return s.IsRedistributable
}

// GetIsStandardLibrary returns the value of IsStandardLibrary.
func (s *Module) GetIsStandardLibrary() OptBool {
	return s.IsStandardLibrary
}

// GetLicenses returns the value of Licenses.
func (s *Module) GetLicenses() []License {
	return s.Licenses
}

// GetPath returns the value of Path.
func (s *Module) GetPath() OptString {
	return s.Path
}

// GetReadme returns the value of Readme.
func (s *Module) GetReadme() OptReadme {
	return s.Readme
}

// GetRepoUrl returns the value of RepoUrl.
func (s *Module) GetRepoUrl() OptString {
	return s.RepoUrl
}

// GetVersion returns the value of Version.
func (s *Module) GetVersion() OptString {
	return s.Version
}

// SetCommitTime sets the value of CommitTime.
func (s *Module) SetCommitTime(val OptDateTime) {
	s.CommitTime = val
}

// SetGoModContents sets the value of GoModContents.
func (s *Module) SetGoModContents(val OptString) {
	s.GoModContents = val
}

// SetHasGoMod sets the value of HasGoMod.
func (s *Module) SetHasGoMod(val OptBool) {
	s.HasGoMod = val
}

// SetIsLatest sets the value of IsLatest.
func (s *Module) SetIsLatest(val OptBool) {
	s.IsLatest = val
}

// SetIsRedistributable sets the value of IsRedistributable.
func (s *Module) SetIsRedistributable(val OptBool) {
	s.IsRedistributable = val
}

// SetIsStandardLibrary sets the value of IsStandardLibrary.
func (s *Module) SetIsStandardLibrary(val OptBool) {
	s.IsStandardLibrary = val
}

// SetLicenses sets the value of Licenses.
func (s *Module) SetLicenses(val []License) {
	s.Licenses = val
}

// SetPath sets the value of Path.
func (s *Module) SetPath(val OptString) {
	s.Path = val
}

// SetReadme sets the value of Readme.
func (s *Module) SetReadme(val OptReadme) {
	s.Readme = val
}

// SetRepoUrl sets the value of RepoUrl.
func (s *Module) SetRepoUrl(val OptString) {
	s.RepoUrl = val
}

// SetVersion sets the value of Version.
func (s *Module) SetVersion(val OptString) {
	s.Version = val
}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptDateTime returns new OptDateTime with value set to v.
func NewOptDateTime(v time.Time) OptDateTime {
	return OptDateTime{
		Value: v,
		Set:   true,
	}
}

// OptDateTime is optional time.Time.
type OptDateTime struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDateTime was set.
func (o OptDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDateTime) Get() (v time.Time, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilAnyArray returns new OptNilAnyArray with value set to v.
func NewOptNilAnyArray(v []jx.Raw) OptNilAnyArray {
	return OptNilAnyArray{
		Value: v,
		Set:   true,
	}
}

// OptNilAnyArray is optional nullable []jx.Raw.
type OptNilAnyArray struct {
	Value []jx.Raw
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilAnyArray was set.
func (o OptNilAnyArray) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilAnyArray) Reset() {
	var v []jx.Raw
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilAnyArray) SetTo(v []jx.Raw) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilAnyArray) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilAnyArray) SetToNull() {
	o.Set = true
	o.Null = true
	var v []jx.Raw
	o.Value = v
}

// IsEmpty returns true if the field was omitted from the payload (not Set and not Null).
func (o OptNilAnyArray) IsEmpty() bool {
	return !o.Set && !o.Null
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilAnyArray) Get() (v []jx.Raw, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilAnyArray) Or(d []jx.Raw) []jx.Raw {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptPaginatedResponse returns new OptPaginatedResponse with value set to v.
func NewOptPaginatedResponse(v PaginatedResponse) OptPaginatedResponse {
	return OptPaginatedResponse{
		Value: v,
		Set:   true,
	}
}

// OptPaginatedResponse is optional PaginatedResponse.
type OptPaginatedResponse struct {
	Value PaginatedResponse
	Set   bool
}

// IsSet returns true if OptPaginatedResponse was set.
func (o OptPaginatedResponse) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptPaginatedResponse) Reset() {
	var v PaginatedResponse
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptPaginatedResponse) SetTo(v PaginatedResponse) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptPaginatedResponse) Get() (v PaginatedResponse, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptPaginatedResponse) Or(d PaginatedResponse) PaginatedResponse {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptReadme returns new OptReadme with value set to v.
func NewOptReadme(v Readme) OptReadme {
	return OptReadme{
		Value: v,
		Set:   true,
	}
}

// OptReadme is optional Readme.
type OptReadme struct {
	Value Readme
	Set   bool
}

// IsSet returns true if OptReadme was set.
func (o OptReadme) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptReadme) Reset() {
	var v Readme
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptReadme) SetTo(v Readme) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptReadme) Get() (v Readme, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptReadme) Or(d Readme) Readme {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/Package
type Package struct {
	Docs     OptString `json:"docs"`
	Goarch   OptString `json:"goarch"`
	Goos     OptString `json:"goos"`
	Imports  []string  `json:"imports"`
	IsLatest OptBool   `json:"isLatest"`
	// Whether the license allows distribution.
	IsRedistributable OptBool   `json:"isRedistributable"`
	IsStandardLibrary OptBool   `json:"isStandardLibrary"`
	Licenses          []License `json:"licenses"`
	ModulePath        OptString `json:"modulePath"`
	Name              OptString `json:"name"`
	Path              OptString `json:"path"`
	Synopsis          OptString `json:"synopsis"`
	Version           OptString `json:"version"`
}

// GetDocs returns the value of Docs.
func (s *Package) GetDocs() OptString {
	return s.Docs
}

// GetGoarch returns the value of Goarch.
func (s *Package) GetGoarch() OptString {
	return s.Goarch
}

// GetGoos returns the value of Goos.
func (s *Package) GetGoos() OptString {
	return s.Goos
}

// GetImports returns the value of Imports.
func (s *Package) GetImports() []string {
	return s.Imports
}

// GetIsLatest returns the value of IsLatest.
func (s *Package) GetIsLatest() OptBool {
	return s.IsLatest
}

// GetIsRedistributable returns the value of IsRedistributable.
func (s *Package) GetIsRedistributable() OptBool {
	return s.IsRedistributable
}

// GetIsStandardLibrary returns the value of IsStandardLibrary.
func (s *Package) GetIsStandardLibrary() OptBool {
	return s.IsStandardLibrary
}

// GetLicenses returns the value of Licenses.
func (s *Package) GetLicenses() []License {
	return s.Licenses
}

// GetModulePath returns the value of ModulePath.
func (s *Package) GetModulePath() OptString {
	return s.ModulePath
}

// GetName returns the value of Name.
func (s *Package) GetName() OptString {
	return s.Name
}

// GetPath returns the value of Path.
func (s *Package) GetPath() OptString {
	return s.Path
}

// GetSynopsis returns the value of Synopsis.
func (s *Package) GetSynopsis() OptString {
	return s.Synopsis
}

// GetVersion returns the value of Version.
func (s *Package) GetVersion() OptString {
	return s.Version
}

// SetDocs sets the value of Docs.
func (s *Package) SetDocs(val OptString) {
	s.Docs = val
}

// SetGoarch sets the value of Goarch.
func (s *Package) SetGoarch(val OptString) {
	s.Goarch = val
}

// SetGoos sets the value of Goos.
func (s *Package) SetGoos(val OptString) {
	s.Goos = val
}

// SetImports sets the value of Imports.
func (s *Package) SetImports(val []string) {
	s.Imports = val
}

// SetIsLatest sets the value of IsLatest.
func (s *Package) SetIsLatest(val OptBool) {
	s.IsLatest = val
}

// SetIsRedistributable sets the value of IsRedistributable.
func (s *Package) SetIsRedistributable(val OptBool) {
	s.IsRedistributable = val
}

// SetIsStandardLibrary sets the value of IsStandardLibrary.
func (s *Package) SetIsStandardLibrary(val OptBool) {
	s.IsStandardLibrary = val
}

// SetLicenses sets the value of Licenses.
func (s *Package) SetLicenses(val []License) {
	s.Licenses = val
}

// SetModulePath sets the value of ModulePath.
func (s *Package) SetModulePath(val OptString) {
	s.ModulePath = val
}

// SetName sets the value of Name.
func (s *Package) SetName(val OptString) {
	s.Name = val
}

// SetPath sets the value of Path.
func (s *Package) SetPath(val OptString) {
	s.Path = val
}

// SetSynopsis sets the value of Synopsis.
func (s *Package) SetSynopsis(val OptString) {
	s.Synopsis = val
}

// SetVersion sets the value of Version.
func (s *Package) SetVersion(val OptString) {
	s.Version = val
}

// Ref: #/components/schemas/PackageImportedBy
type PackageImportedBy struct {
	ImportedBy OptPaginatedResponse `json:"importedBy"`
	ModulePath OptString            `json:"modulePath"`
	Version    OptString            `json:"version"`
}

// GetImportedBy returns the value of ImportedBy.
func (s *PackageImportedBy) GetImportedBy() OptPaginatedResponse {
	return s.ImportedBy
}

// GetModulePath returns the value of ModulePath.
func (s *PackageImportedBy) GetModulePath() OptString {
	return s.ModulePath
}

// GetVersion returns the value of Version.
func (s *PackageImportedBy) GetVersion() OptString {
	return s.Version
}

// SetImportedBy sets the value of ImportedBy.
func (s *PackageImportedBy) SetImportedBy(val OptPaginatedResponse) {
	s.ImportedBy = val
}

// SetModulePath sets the value of ModulePath.
func (s *PackageImportedBy) SetModulePath(val OptString) {
	s.ModulePath = val
}

// SetVersion sets the value of Version.
func (s *PackageImportedBy) SetVersion(val OptString) {
	s.Version = val
}

// Ref: #/components/schemas/PackageSymbols
type PackageSymbols struct {
	ModulePath OptString            `json:"modulePath"`
	Symbols    OptPaginatedResponse `json:"symbols"`
	Version    OptString            `json:"version"`
}

// GetModulePath returns the value of ModulePath.
func (s *PackageSymbols) GetModulePath() OptString {
	return s.ModulePath
}

// GetSymbols returns the value of Symbols.
func (s *PackageSymbols) GetSymbols() OptPaginatedResponse {
	return s.Symbols
}

// GetVersion returns the value of Version.
func (s *PackageSymbols) GetVersion() OptString {
	return s.Version
}

// SetModulePath sets the value of ModulePath.
func (s *PackageSymbols) SetModulePath(val OptString) {
	s.ModulePath = val
}

// SetSymbols sets the value of Symbols.
func (s *PackageSymbols) SetSymbols(val OptPaginatedResponse) {
	s.Symbols = val
}

// SetVersion sets the value of Version.
func (s *PackageSymbols) SetVersion(val OptString) {
	s.Version = val
}

// Ref: #/components/schemas/PackagesResponse
type PackagesResponse struct {
	IsStandardLibrary OptBool              `json:"isStandardLibrary"`
	ModulePath        OptString            `json:"modulePath"`
	Packages          OptPaginatedResponse `json:"packages"`
	Version           OptString            `json:"version"`
}

// GetIsStandardLibrary returns the value of IsStandardLibrary.
func (s *PackagesResponse) GetIsStandardLibrary() OptBool {
	return s.IsStandardLibrary
}

// GetModulePath returns the value of ModulePath.
func (s *PackagesResponse) GetModulePath() OptString {
	return s.ModulePath
}

// GetPackages returns the value of Packages.
func (s *PackagesResponse) GetPackages() OptPaginatedResponse {
	return s.Packages
}

// GetVersion returns the value of Version.
func (s *PackagesResponse) GetVersion() OptString {
	return s.Version
}

// SetIsStandardLibrary sets the value of IsStandardLibrary.
func (s *PackagesResponse) SetIsStandardLibrary(val OptBool) {
	s.IsStandardLibrary = val
}

// SetModulePath sets the value of ModulePath.
func (s *PackagesResponse) SetModulePath(val OptString) {
	s.ModulePath = val
}

// SetPackages sets the value of Packages.
func (s *PackagesResponse) SetPackages(val OptPaginatedResponse) {
	s.Packages = val
}

// SetVersion sets the value of Version.
func (s *PackagesResponse) SetVersion(val OptString) {
	s.Version = val
}

// Ref: #/components/schemas/PaginatedResponse
type PaginatedResponse struct {
	Items         OptNilAnyArray `json:"items"`
	NextPageToken OptString      `json:"nextPageToken"`
	Total         OptInt         `json:"total"`
}

// GetItems returns the value of Items.
func (s *PaginatedResponse) GetItems() OptNilAnyArray {
	return s.Items
}

// GetNextPageToken returns the value of NextPageToken.
func (s *PaginatedResponse) GetNextPageToken() OptString {
	return s.NextPageToken
}

// GetTotal returns the value of Total.
func (s *PaginatedResponse) GetTotal() OptInt {
	return s.Total
}

// SetItems sets the value of Items.
func (s *PaginatedResponse) SetItems(val OptNilAnyArray) {
	s.Items = val
}

// SetNextPageToken sets the value of NextPageToken.
func (s *PaginatedResponse) SetNextPageToken(val OptString) {
	s.NextPageToken = val
}

// SetTotal sets the value of Total.
func (s *PaginatedResponse) SetTotal(val OptInt) {
	s.Total = val
}

// Ref: #/components/schemas/Readme
type Readme struct {
	Contents OptString `json:"contents"`
	Filepath OptString `json:"filepath"`
}

// GetContents returns the value of Contents.
func (s *Readme) GetContents() OptString {
	return s.Contents
}

// GetFilepath returns the value of Filepath.
func (s *Readme) GetFilepath() OptString {
	return s.Filepath
}

// SetContents sets the value of Contents.
func (s *Readme) SetContents(val OptString) {
	s.Contents = val
}

// SetFilepath sets the value of Filepath.
func (s *Readme) SetFilepath(val OptString) {
	s.Filepath = val
}
